Change --hub_url short option string to -H
Otherwise, I get:

    Traceback (most recent call last):
      File "/tmp/datahub/scripts/./delete-unused-users.py", line 116, in <module>
        argparser.add_argument(
      File "/usr/lib/python3.11/argparse.py", line 1480, in add_argument
        return self._add_action(action)
               ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/argparse.py", line 1862, in _add_action
        self._optionals._add_action(action)
      File "/usr/lib/python3.11/argparse.py", line 1682, in _add_action
        action = super(_ArgumentGroup, self)._add_action(action)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/argparse.py", line 1494, in _add_action
        self._check_conflict(action)
      File "/usr/lib/python3.11/argparse.py", line 1631, in _check_conflict
        conflict_handler(action, confl_optionals)
      File "/usr/lib/python3.11/argparse.py", line 1640, in _handle_conflict_error
        raise ArgumentError(action, message % conflict_string)
    argparse.ArgumentError: argument -h/--hub_url: conflicting option string: -h