Increase size of prob140 hub-db
Was causing errors as the disk was full

```
E 2021-09-13 19:58:11.138 JupyterHub base:429] Error getting current user
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 422, in get_current_user
        user = self.get_current_user_cookie()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 414, in get_current_user_cookie
        return self._user_for_cookie(self.hub.cookie_name)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/handlers/base.py", line 394, in _user_for_cookie
        u = self.db.query(orm.User).filter(orm.User.cookie_id == cookie_id).first()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2750, in first
        return self.limit(1)._iter().first()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 2834, in _iter
        result = self.session.execute(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1688, in execute
        conn = self._connection_for_bind(bind)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
        return self._transaction._connection_for_bind(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
        self._assert_active()
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
        raise sa_exc.PendingRollbackError(
    sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
    (sqlite3.OperationalError) database or disk is full
    [SQL: UPDATE api_tokens SET last_activity=? WHERE api_tokens.id = ?]
    [parameters: ('2021-09-13 19:58:11.012862', 93159)]
    (Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)

```

Ref https://github.com/berkeley-dsep-infra/datahub/issues/2242