Revert today's repo2docker changes.
Since the update, user servers on a11y fail with:

  Traceback (most recent call last):
    File "/srv/conda/envs/notebook/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 32, in import_item
      pak = getattr(module, obj)
  AttributeError: module 'notebook.base.handlers' has no attribute 'IPythonHandler'